import { BlueprintCatalog } from './blueprintTypes';

// This file is generated by scripts/generate-blueprints.ts. Do not edit by hand.
export const blueprintCatalog: BlueprintCatalog = [
  {
    "id": "chat",
    "title": "Chat",
    "component": "ChatConsole",
    "description": "Message console placeholder for operator collaboration.",
    "dimensions": {
      "width": "50%",
      "height": "50%"
    },
    "position": {
      "x": "center",
      "y": "center"
    }
  },
  {
    "id": "imagery",
    "title": "Imagery Analysis",
    "component": "ImageryWorkbench",
    "description": "Placeholder imagery analysis workbench ready for annotation tools.",
    "dimensions": {
      "width": "50%",
      "height": "50%"
    },
    "position": {
      "x": "center",
      "y": "center"
    }
  },
  {
    "id": "map",
    "title": "Map Viewer",
    "component": "MapViewport",
    "description": "Base map visualization shell for future layers and overlays.",
    "dimensions": {
      "width": "50%",
      "height": "50%"
    },
    "position": {
      "x": "center",
      "y": "center"
    }
  },
  {
    "id": "planner",
    "title": "Mission Planning",
    "component": "PlannerBoard",
    "description": "Layout for mission planning timeline and waypoint editors.",
    "dimensions": {
      "width": "50%",
      "height": "50%"
    },
    "position": {
      "x": "center",
      "y": "center"
    }
  },
  {
    "id": "test",
    "title": "GoldenLayout Test",
    "component": "GoldenLayoutTest",
    "description": "Sandbox window that mirrors the legacy GoldenLayout test template.",
    "dimensions": {
      "width": "50%",
      "height": "50%"
    },
    "position": {
      "x": "center",
      "y": "center"
    }
  },
  {
    "id": "viewer",
    "title": "Viewer",
    "component": "MediaViewer",
    "description": "Flexible viewer shell for images and live video feeds.",
    "dimensions": {
      "width": "50%",
      "height": "50%"
    },
    "position": {
      "x": "center",
      "y": "center"
    }
  }
];
