// Generated from FastAPI OpenAPI schema. Do not edit by hand.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/{db_name}": {
    /** List Documents */
    get: operations["list_documents_api__db_name__get"];
    /** Insert Document */
    post: operations["insert_document_api__db_name__post"];
  };
  "/api/{db_name}/{key}/{value}": {
    /** Update Document */
    put: operations["update_document_api__db_name___key___value__put"];
    /** Delete Document */
    delete: operations["delete_document_api__db_name___key___value__delete"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** DocumentPayload */
    DocumentPayload: {
      /** Data */
      data: {
        [key: string]: unknown;
      };
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** UpdatePayload */
    UpdatePayload: {
      /** Data */
      data: {
        [key: string]: unknown;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List Documents */
  list_documents_api__db_name__get: {
    parameters: {
      query?: {
        key?: string | null;
        value?: string | null;
      };
      header?: {
        "x-auth-token"?: string | null;
      };
      path: {
        /** @description Database name */
        db_name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Insert Document */
  insert_document_api__db_name__post: {
    parameters: {
      header?: {
        "x-auth-token"?: string | null;
      };
      path: {
        /** @description Database name */
        db_name: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DocumentPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Document */
  update_document_api__db_name___key___value__put: {
    parameters: {
      header?: {
        "x-auth-token"?: string | null;
      };
      path: {
        /** @description Database name */
        db_name: string;
        key: string;
        value: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Document */
  delete_document_api__db_name___key___value__delete: {
    parameters: {
      header?: {
        "x-auth-token"?: string | null;
      };
      path: {
        /** @description Database name */
        db_name: string;
        key: string;
        value: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
