import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import { BlueprintCatalog, WindowBlueprint } from '../src/blueprints/blueprintTypes';

const CURRENT_PATH = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(CURRENT_PATH, '..');
const BLUEPRINT_DIR = path.join(PROJECT_ROOT, 'blueprints');
const OUTPUT_PATH = path.join(PROJECT_ROOT, 'src/blueprints/generated.ts');

const blueprintFiles = fs
  .readdirSync(BLUEPRINT_DIR, { withFileTypes: true })
  .filter((entry) => entry.isFile() && (entry.name.endsWith('.yaml') || entry.name.endsWith('.yml')))
  .map((entry) => entry.name)
  .sort((left, right) => left.localeCompare(right));

if (blueprintFiles.length === 0) {
  throw new Error(`No blueprint YAML files found in ${BLUEPRINT_DIR}.`);
}

const blueprints: BlueprintCatalog = blueprintFiles.map((fileName) => {
  const blueprintPath = path.join(BLUEPRINT_DIR, fileName);
  const source = fs.readFileSync(blueprintPath, 'utf8');
  const parsed = parse(source) as Partial<WindowBlueprint>;
  const missingFields = ['id', 'title', 'component', 'dimensions', 'position'].filter(
    (key) => parsed[key as keyof WindowBlueprint] === undefined
  );

  if (missingFields.length > 0) {
    throw new Error(`Blueprint ${fileName} is missing fields: ${missingFields.join(', ')}.`);
  }

  return {
    id: parsed.id as string,
    title: parsed.title as string,
    component: parsed.component as string,
    description: parsed.description,
    dimensions: parsed.dimensions as WindowBlueprint['dimensions'],
    position: parsed.position as WindowBlueprint['position']
  };
});

const fileHeader = [
  "import { BlueprintCatalog } from './blueprintTypes';",
  '',
  '// This file is generated by scripts/generate-blueprints.ts. Do not edit by hand.'
].join('\n');

const fileBody = `export const blueprintCatalog: BlueprintCatalog = ${JSON.stringify(blueprints, null, 2)};`;

fs.writeFileSync(OUTPUT_PATH, `${fileHeader}\n${fileBody}\n`, 'utf8');
